// demos/vue-demo/src/components/Navigation.vue
<template>
  <nav class="navbar">
    <div class="navbar-container">
      <router-link to="/" class="navbar-brand"> Nhost Vue Demo </router-link>

      <div class="navbar-links">
        <template v-if="isAuthenticated">
          <router-link
            to="/profile"
            class="nav-link"
            :class="{ active: $route.path === '/profile' }"
          >
            Profile
          </router-link>
          <button @click="handleSignOut" class="nav-link" :disabled="isLoading">
            {{ isLoading ? 'Signing Out...' : 'Sign Out' }}
          </button>
        </template>

        <template v-else>
          <router-link to="/signin" class="nav-link" :class="{ active: $route.path === '/signin' }">
            Sign In
          </router-link>
          <router-link to="/signup" class="nav-link" :class="{ active: $route.path === '/signup' }">
            Sign Up
          </router-link>
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../lib/nhost/auth'

const { nhost, isAuthenticated, session } = useAuth()
const router = useRouter()
const isLoading = ref(false)

const handleSignOut = async () => {
  isLoading.value = true

  try {
    if (session.value) {
      await nhost.auth.signOut({
        refreshToken: session.value.refreshToken,
      })
    }
    router.push('/')
  } catch (error) {
    console.error('Error signing out:', error)
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
button.nav-link {
  background: none;
  border: none;
  cursor: pointer;
}

button.nav-link:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// demos/nextjs-demo/src/app/components/Navigation.tsx
'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useNhost } from '../lib/nhost-provider';
import { useState } from 'react';

export default function Navigation() {
  const { session, signout } = useNhost();
  const pathname = usePathname();
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);

  const isActive = (path: string) => {
    return pathname === path;
  };

  const handleSignOut = async () => {
    setIsLoading(true);
    try {
      signout();
      router.push('/signin');
    } catch (err) {
      console.error('Error signing out:', err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="flex items-center">
          <span className="navbar-brand">Nhost Demo</span>
          <div className="navbar-links">
            {session ? (
              <>
                <Link 
                  href="/profile" 
                  className={`nav-link ${isActive('/profile') ? 'active' : ''}`}
                >
                  Profile
                </Link>
                <Link 
                  href="/upload" 
                  className={`nav-link ${isActive('/upload') ? 'active' : ''}`}
                >
                  Upload
                </Link>
              </>
            ) : (
              <>
                <Link 
                  href="/" 
                  className={`nav-link ${isActive('/') ? 'active' : ''}`}
                >
                  Sign Up
                </Link>
                <Link 
                  href="/signin" 
                  className={`nav-link ${isActive('/signin') ? 'active' : ''}`}
                >
                  Sign In
                </Link>
              </>
            )}
          </div>
        </div>

        {session && (
          <div>
            <button
              onClick={handleSignOut}
              disabled={isLoading}
              className="icon-button"
              title="Sign Out"
            >
              {isLoading ? (
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M12 6v6"></path>
                </svg>
              ) : (
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                  <polyline points="16 17 21 12 16 7"></polyline>
                  <line x1="21" y1="12" x2="9" y2="12"></line>
                </svg>
              )}
            </button>
          </div>
        )}
      </div>
    </nav>
  );
}
