// demos/graphql-theguild-codegen/src/components/Navigation.tsx
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../lib/nhost/AuthProvider";
import { type JSX } from "react";

export default function Navigation(): JSX.Element {
  const { isAuthenticated, nhost, session } = useAuth();
  const location = useLocation();

  // Helper function to determine if a link is active
  const isActive = (path: string): string => {
    return location.pathname === path ? "active" : "";
  };

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="flex items-center">
          <span className="navbar-brand">Nhost Demo</span>
          <div className="navbar-links">
            {isAuthenticated ? (
              <>
                <Link
                  to="/profile"
                  className={`nav-link ${isActive("/profile")}`}
                >
                  Profile
                </Link>
              </>
            ) : (
              <>
                <Link
                  to="/signin"
                  className={`nav-link ${isActive("/signin")}`}
                >
                  Sign In
                </Link>
                <Link
                  to="/signup"
                  className={`nav-link ${isActive("/signup")}`}
                >
                  Sign Up
                </Link>
              </>
            )}
          </div>
        </div>

        {isAuthenticated && (
          <div>
            <button
              onClick={async () => {
                if (session) {
                  await nhost.auth.signOut({
                    refreshToken: session.refreshToken,
                  });
                }
              }}
              className="icon-button"
              title="Sign Out"
            >
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
                <polyline points="16 17 21 12 16 7" />
                <line x1="21" y1="12" x2="9" y2="12" />
              </svg>
            </button>
          </div>
        )}
      </div>
    </nav>
  );
}

// demos/vue-demo/src/components/Navigation.vue
<template>
  <nav class="navbar">
    <div class="navbar-container">
      <router-link to="/" class="navbar-brand"> Nhost Vue Demo </router-link>

      <div class="navbar-links">
        <template v-if="isAuthenticated">
          <router-link
            to="/profile"
            class="nav-link"
            :class="{ active: $route.path === '/profile' }"
          >
            Profile
          </router-link>
          <button @click="handleSignOut" class="nav-link" :disabled="isLoading">
            {{ isLoading ? 'Signing Out...' : 'Sign Out' }}
          </button>
        </template>

        <template v-else>
          <router-link to="/signin" class="nav-link" :class="{ active: $route.path === '/signin' }">
            Sign In
          </router-link>
          <router-link to="/signup" class="nav-link" :class="{ active: $route.path === '/signup' }">
            Sign Up
          </router-link>
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../lib/nhost/auth'

const { nhost, isAuthenticated, session } = useAuth()
const router = useRouter()
const isLoading = ref(false)

const handleSignOut = async () => {
  isLoading.value = true

  try {
    if (session.value) {
      await nhost.auth.signOut({
        refreshToken: session.value.refreshToken,
      })
    }
    router.push('/')
  } catch (error) {
    console.error('Error signing out:', error)
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
button.nav-link {
  background: none;
  border: none;
  cursor: pointer;
}

button.nav-link:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>
