// demos/vue-demo/src/App.vue
<template>
  <div class="flex-col min-h-screen">
    <Navigation />
    <main class="max-w-2xl mx-auto p-6 w-full">
      <router-view />
    </main>
    <footer>
      <p class="text-sm text-center" style="color: var(--text-muted)">
        © {{ new Date().getFullYear() }} Nhost Demo
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import Navigation from './components/Navigation.vue'
</script>

<style>
@import './assets/main.css';

#app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
</style>

// demos/react-demo/src/App.tsx
import { Suspense, lazy, JSX } from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";
import { AuthProvider } from "./lib/nhost/AuthProvider";
import Navigation from "./components/Navigation";
import ProtectedRoute from "./components/ProtectedRoute";
import Home from "./pages/Home";
import SignIn from "./pages/SignIn";
import SignUp from "./pages/SignUp";
import Profile from "./pages/Profile";
import Upload from "./pages/Upload";
import Verify from "./pages/Verify";

const MfaVerification = lazy(() => import("./pages/signin/mfa"));

const App = (): JSX.Element => {
  return (
    <AuthProvider>
      <Router>
        <div className="flex-col min-h-screen">
          <Navigation />
          <main className="max-w-2xl mx-auto p-6 w-full">
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/signin" element={<SignIn />} />
              <Route
                path="/signin/mfa"
                element={
                  <Suspense
                    fallback={
                      <div className="loading-container">Loading...</div>
                    }
                  >
                    <MfaVerification />
                  </Suspense>
                }
              />
              <Route path="/signup" element={<SignUp />} />
              <Route path="/verify" element={<Verify />} />
              <Route element={<ProtectedRoute />}>
                <Route path="/profile" element={<Profile />} />
                <Route path="/upload" element={<Upload />} />
              </Route>
              <Route path="*" element={<Navigate to="/" />} />
            </Routes>
          </main>
          <footer>
            <p
              className="text-sm text-center"
              style={{ color: "var(--text-muted)" }}
            >
              © {new Date().getFullYear()} Nhost Demo
            </p>
          </footer>
        </div>
      </Router>
    </AuthProvider>
  );
};

export default App;
