// demos/sveltekit-demo/src/lib/components/MagicLinkForm.svelte
<script lang="ts">
  import { nhost } from '$lib/nhost/auth';
  import type { ErrorResponse } from '@nhost/nhost-js/auth';
  import type { FetchError } from '@nhost/nhost-js/fetch';

  interface Props {
    buttonLabel?: string;
  }

  let { buttonLabel = 'Send Magic Link' }: Props = $props();

  let email = '';
  let isLoading = false;
  let success = false;
  let error: string | null = null;

  async function handleSubmit(e: Event) {
    e.preventDefault();
    isLoading = true;
    error = null;

    try {
      await nhost.auth.signInPasswordlessEmail({
        email,
        options: {
          redirectTo: `${window.location.origin}/verify`,
        },
      });

      success = true;
    } catch (err) {
      const fetchError = err as FetchError<ErrorResponse>;
      error = `An error occurred while sending the magic link: ${fetchError.message}`;
    } finally {
      isLoading = false;
    }
  }

  function tryAgain() {
    success = false;
    email = '';
    error = null;
  }
</script>

{#if success}
  <div class="text-center">
    <p class="mb-4">Magic link sent! Check your email to sign in.</p>
    <button onclick={tryAgain} class="btn btn-secondary">
      Try again
    </button>
  </div>
{:else}
  <form onsubmit={handleSubmit} class="space-y-5">
    <div>
      <label for="magic-email">Email</label>
      <input
        id="magic-email"
        type="email"
        bind:value={email}
        required
      />
    </div>

    {#if error}
      <div class="alert alert-error">{error}</div>
    {/if}

    <button
      type="submit"
      class="btn btn-primary w-full"
      disabled={isLoading}
    >
      {isLoading ? 'Sending...' : buttonLabel}
    </button>
  </form>
{/if}

// demos/react-demo/src/components/MagicLinkForm.tsx
import React, { JSX, useState } from "react";
import { useAuth } from "../lib/nhost/AuthProvider";
import { FetchResponse, ErrorResponse } from "@nhost/nhost-js/auth";

interface MagicLinkFormProps {
  buttonLabel?: string;
}

export default function MagicLinkForm({
  buttonLabel = "Send Magic Link",
}: MagicLinkFormProps): JSX.Element {
  const [email, setEmail] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [success, setSuccess] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const { nhost } = useAuth();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);

    try {
      await nhost.auth.signInPasswordlessEmail({
        email,
        options: {
          redirectTo: `${window.location.origin}/verify`,
        },
      });

      setSuccess(true);
    } catch (err) {
      const error = err as FetchResponse<ErrorResponse>;
      setError(error.body.message || "An unexpected error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  if (success) {
    return (
      <div className="text-center">
        <p className="mb-4">Magic link sent! Check your email to sign in.</p>
        <button onClick={() => setSuccess(false)} className="btn btn-secondary">
          Try again
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <div>
        <label htmlFor="magic-email">Email</label>
        <input
          id="magic-email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      <button
        type="submit"
        className="btn btn-primary w-full"
        disabled={isLoading}
      >
        {isLoading ? "Sending..." : buttonLabel}
      </button>
    </form>
  );
}
